name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Node.js v14
      uses: actions/setup-node@v3
      with:
        node-version: 14
    
    - name: Install Twilio CLI
      run: npm install -g twilio-cli && twilio plugins:install @twilio-labs/plugin-flex@5.1.0
    
    - name: Install and run tests
      run: npm install-ci-test